/**
 * Generates `example/theme/cityscape.css` from a bundled `@marianmeres/design-tokens` theme,
 * under the `--app-color-*` prefix the control panel reads. Run with:
 *
 *   deno task theme:build
 *
 * Light tokens live on `:root`, dark tokens on `:root.dark` — the example sets `class="dark"`
 * so the panel picks up the dark surface/foreground/border/primary tokens.
 */

import { generateThemeCss } from "@marianmeres/design-tokens";
import { bundledThemeNames, getBundledTheme } from "@marianmeres/design-tokens/themes";

// Pick a calm, cool theme that suits the night skyline; fall back gracefully.
const preferred = ["slateTealOcean", "indigoAmber", "mistVioletAurora"];
const name = preferred.find((n) => bundledThemeNames.includes(n)) ??
	bundledThemeNames[0];
const theme = getBundledTheme(name);
if (!theme) throw new Error(`Bundled theme not found: ${name}`);

const css =
	`/* GENERATED by example/theme/_generate.ts from design-tokens theme "${name}". */\n` +
	generateThemeCss(theme, "app");

await Deno.writeTextFile(new URL("./cityscape.css", import.meta.url), css);
console.error(`Wrote example/theme/cityscape.css (theme: ${name})`);
