/**
 * Generates `example/theme/tokens.css` for the example SPA, under the `--app-color-*` prefix the
 * control panel reads. Run with:
 *
 *   deno task example:theme
 *
 * Because all three worlds now share one document (the SPA), their panel themes can't each own
 * `:root` like the old per-page sheets did — they would clobber each other. Instead every world's
 * tokens are scoped to a `[data-world="…"]` attribute the router sets on the active stage, so the
 * right palette cascades into that world's panel and nowhere else:
 *
 *   • city   → a calm, cool **dark** theme (night skyline)
 *   • nature → a warm **light** theme (a bright day valley)
 *
 * `generateThemeCss()` only emits `:root` / `:root.dark`, so we drop to the lower-level
 * `generateCssTokens()` + `toCssString(tokens, selector)` to choose the mode *and* the selector.
 */

import {
	generateCssTokens,
	type ThemeSchema,
	toCssString,
} from "@marianmeres/design-tokens";
import { bundledThemeNames, getBundledTheme } from "@marianmeres/design-tokens/themes";

/** Pick the first available bundled theme from a preference list (graceful fallback). */
function pick(preferred: string[]): { name: string; theme: ThemeSchema } {
	const name = preferred.find((n) => bundledThemeNames.includes(n)) ??
		bundledThemeNames[0];
	const theme = getBundledTheme(name);
	if (!theme) throw new Error(`Bundled theme not found: ${name}`);
	return { name, theme };
}

// A calm, cool theme for the night worlds; a warm, leafy one for the day valley.
const cool = pick(["slateTealOcean", "indigoAmber", "mistVioletAurora"]);
const warm = pick(["emeraldAmberForest", "emeraldForest", "limeForest"]);

/** Emit one world's tokens (in the chosen mode) scoped to `[data-world="<world>"]`. */
function block(world: string, theme: ThemeSchema, mode: "light" | "dark"): string {
	const schema = mode === "dark" ? theme.dark ?? theme.light : theme.light;
	const tokens = generateCssTokens(schema, "app", mode);
	return toCssString(tokens, `[data-world="${world}"]`);
}

const css = [
	`/* GENERATED by example/theme/_generate.ts — do not edit by hand.`,
	`   Run: deno task example:theme`,
	`   city = "${cool.name}" (dark) · nature = "${warm.name}" (light). */`,
	"",
	block("city", cool.theme, "dark"),
	block("nature", warm.theme, "light"),
].join("\n");

const out = new URL("./tokens.css", import.meta.url);
await Deno.writeTextFile(out, css + "\n");

// design-tokens emits column-aligned declarations; run the result through `deno fmt` so a
// regenerated tokens.css stays consistent with the repo's formatting (and `deno fmt --check` is happy).
await new Deno.Command("deno", { args: ["fmt", "--quiet", out.pathname] }).output();

console.error(
	`Wrote example/theme/tokens.css (city: ${cool.name} dark · nature: ${warm.name} light)`,
);
