/**
 * Generates `example-nature/theme/naturescape.css` from a bundled `@marianmeres/design-tokens`
 * theme, under the `--app-color-*` prefix the control panel reads. Run with:
 *
 *   deno task example-nature:theme
 *
 * Light tokens live on `:root`, dark tokens on `:root.dark` — the nature example stays in light
 * mode (a bright day) so the panel picks up the light surface/foreground/border/primary tokens.
 */

import { generateThemeCss } from "@marianmeres/design-tokens";
import { bundledThemeNames, getBundledTheme } from "@marianmeres/design-tokens/themes";

// Pick a calm forest-green theme that suits the sunlit valley; fall back gracefully.
const preferred = ["emeraldAmberForest", "amberOliveSafari", "monokaiGreen", "olive"];
const name = preferred.find((n) => bundledThemeNames.includes(n)) ??
	bundledThemeNames[0];
const theme = getBundledTheme(name);
if (!theme) throw new Error(`Bundled theme not found: ${name}`);

const css =
	`/* GENERATED by example-nature/theme/_generate.ts from design-tokens theme "${name}". */\n` +
	generateThemeCss(theme, "app");

await Deno.writeTextFile(new URL("./naturescape.css", import.meta.url), css);
console.error(`Wrote example-nature/theme/naturescape.css (theme: ${name})`);
